name: 01 - Building Blocks
on:
  workflow dispatch:
jobs:
  hello job:
    runs: ubuntu latest
    steps:
      - run: echo "hello world!"
  goodbye job:
    runs: ubuntu latest
    steps:
      - run: echo "goodbye world"
