name: 02 - Workflow Events
on:
  pull_request:
  # workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Show the trigger started by a(n) ${{ github.event_name }} event."
