name: 02 - Workflow Events
on:
  schedule:
    - cron: '* * * * *'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Show the trigger"
          date