name: 02 - Workflow Events
on:
#  push:
 schedule:
    - cron: '* * * * *'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Show the trigger"